graphhopper:
  datareader.file: transit_data/new_york_city_street_network_nyc_cutout_2019_07.osm.pbf
  gtfs.file: transit_data/mta_manhattan_gtfs_20190112_20190427.zip,transit_data/mta_nyc_subway_gtfs_20181104_20190427.zip
  graph.location: transit_data/graphhopper
  graph.flag_encoders: foot

server:
  min_threads: 4
  max_threads: 8
  application_connectors:
    - type: http
      port: 8998
      # for security reasons bind (localhost does not work with k8s svcs)
      bind_host: 0.0.0.0
      acceptor_threads: 1
      selector_threads: 2
      accept_queue_size: 8
  request_log:
    appenders: []
