graphhopper:
  graph.location: transit_data/graphhopper
  routing.ch.disabling_allowed: true
  routing.max_visited_nodes: 1500000

  # graph.bytes_for_flags: 112

  # Uncomment this if the export was done with turn-restriction-aware contraction hierarchies
  # prepare.ch.edge_based: edge_and_node

  #  datareader.file: oregon-latest.osm.pbf
  #  graph.flag_encoders: car|turn_costs=true
  #  graph.bytes_for_flags: 64
  #
  #  prepare.ch.weightings: fastest

  profiles:
    - name: fastest_car_2
      vehicle: car_2
      weighting: fastest
    - name: fastest_car_8
      vehicle: car_8
      weighting: fastest
    - name: fastest_car_13
      vehicle: car_13
      weighting: fastest
    - name: fastest_car_18
      vehicle: car_18
      weighting: fastest
    - name: best_bike
      vehicle: bike
      weighting: fastest
    - name: fastest_foot
      vehicle: foot
      weighting: fastest
    - name: fastest_truck
      vehicle: truck
      weighting: fastest

server:
  min_threads: 4
  max_threads: 8
  application_connectors:
    - type: http
      port: 8998
      # for security reasons bind (localhost does not work with k8s svcs)
      bind_host: 0.0.0.0
      acceptor_threads: 1
      selector_threads: 2
      accept_queue_size: 8
  request_log:
    appenders: []
