ARG BASE_IMAGE
FROM $BASE_IMAGE as base

COPY ./full_usa.osm.pbf ./

RUN java -Xmx13g -Ddw.graphhopper.datareader.file=full_usa.osm.pbf \
  -Ddw.graphhopper.validation=false -classpath web/target/graphhopper-web-1.0-SNAPSHOT.jar \
  com.graphhopper.http.GraphHopperApplication validate-gtfs gtfs_validation_gh_config.yaml \
  && rm ./full_usa.osm.pbf

ENV GTFS_FOLDER "./"
COPY ${GTFS_FOLDER} ./gtfs

CMD ./run_gtfs_validation.sh
