ARG BASE_IMAGE
FROM $BASE_IMAGE as base

COPY ./full_usa.osm.pbf ./

RUN java -Xmx115g -Ddw.graphhopper.datareader.file=full_usa.osm.pbf \
  -Ddw.graphhopper.validation=false -classpath web/target/graphhopper-web-1.0-SNAPSHOT.jar \
  com.graphhopper.http.GraphHopperApplication validate-gtfs gtfs_validation_gh_config.yaml \
  && rm ./full_usa.osm.pbf

# Assumes that folder containing gtfs files is mounted as volume at /gtfs/
CMD ./run_gtfs_validation.sh
