# Configuration file for standard GraphHopper routers.
# 1 profile loaded with default speeds is defined for each vehicle type

graphhopper:
  datareader.file: 
  graph.location: transit_data/graphhopper
  routing.ch.disabling_allowed: true
  routing.max_visited_nodes: 1500000
  graph.flag_encoders: car,bike,foot,truck
  prepare.ch.threads: 16

  # Profiles specifying vehicle and weightings for each mode type.
  # For nationwide export, save time by not building contraction hierarchies
  profiles:
    - name: car
      vehicle: car
      weighting: fastest
    - name: bike
      vehicle: bike
      weighting: fastest
    - name: foot
      vehicle: foot
      weighting: fastest
    - name: truck
      vehicle: truck
      weighting: fastest

server:
  min_threads: 4
  max_threads: 8
  application_connectors:
    - type: http
      port: 8998
      # for security reasons bind (localhost does not work with k8s svcs)
      bind_host: 0.0.0.0
      acceptor_threads: 1
      selector_threads: 2
      accept_queue_size: 8
  request_log:
    appenders: []
