# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  publish-docker:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: &setup_gcloud
          name: Setup gcloud
          command: |
            echo ${GCLOUD_SERVICE_KEY} | base64 -d > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project model-159019
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Choose a tag
          command: git rev-parse --short=8 HEAD > /tmp/tag
      - run:
          name: Build base image
          command: docker build --build-arg GRAPHHOPPER_TOKEN=$GRAPHHOPPER_TOKEN --build-arg GIT_USER_ID=$GIT_USER_ID --build-arg GIT_PERSONAL_ACCESS=$GIT_PERSONAL_ACCESS . -f Dockerfile.build -t us.gcr.io/model-159019/gh:$(cat /tmp/tag)_build
      - run:
          name: Download Mini Norcal Test Files
          command: |
            set -o errexit
            set -o nounset
            set -o pipefail
            set -o xtrace

            gsutil -m cp $MININORCAL_OSM_PATH ./test-data/mini_nor_cal.osm.pbf
            mkdir ./test-data/gtfs/
            gsutil -m cp $MININORCAL_GTFS_PATH - | tar -C ./test-data/gtfs/ -xvf -
            sed -i -e "s/datareader.file: /datareader.file: .\/test-data\/mini_nor_cal.osm.pbf/g" ./default_gh_config.yaml
            export GTFS_FILE_LIST=$(find ./test-data/gtfs/ -type f -printf '%p,' | head -c -1)
            sed -i -e "s/gtfs.file: /gtfs.file: ${GTFS_FILE_LIST//\//\\/}/g" ./default_gh_config.yaml
      - run:
          name: Run Tests
          command: docker run us.gcr.io/model-159019/gh:$(cat /tmp/tag)_build /bin/bash -c "mvn test"
      - run:
          name: Build server image
          command: docker build --build-arg BASE_IMAGE=us.gcr.io/model-159019/gh:$(cat /tmp/tag)_build . -f Dockerfile.server -t us.gcr.io/model-159019/gh:$(cat /tmp/tag)
      - run:
          name: Push image
          command: gcloud docker -- push us.gcr.io/model-159019/gh:$(cat /tmp/tag)
workflows:
  version: 2
  build-and-publish:
    jobs:
      - publish-docker
