# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  maven: circleci/maven@1.2.0

jobs:
  publish-docker:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: &setup_gcloud
          name: Setup gcloud
          command: |
            echo ${GCLOUD_SERVICE_KEY} | base64 -d > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project model-159019
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Choose a tag
          command: git rev-parse --short=8 HEAD > /tmp/tag
      - run:
          name: Build image
          command: docker build --build-arg GRAPHHOPPER_TOKEN=$GRAPHHOPPER_TOKEN --build-arg GIT_USER_ID=$GIT_USER_ID --build-arg GIT_PERSONAL_ACCESS=$GIT_PERSONAL_ACCESS . -f Dockerfile.model -t us.gcr.io/model-159019/gh:$(cat /tmp/tag)
      - run:
          name: Push image
          command: gcloud docker -- push us.gcr.io/model-159019/gh:$(cat /tmp/tag)

workflows:
  version: 2
  build-and-publish:
    jobs:
      - publish-docker
  maven_test:
    jobs:
      - maven/test:
          app_src_directory: ~/repo
          settings_file: maven_settings.xml
          command: -DGRAPHHOPPER_TOKEN=$GRAPHHOPPER_TOKEN -DGIT_USER_ID=$GIT_USER_ID -DGIT_PERSONAL_ACCESS=$GIT_PERSONAL_ACCESS test
