# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  publish-docker:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: &setup_gcloud
          name: Setup gcloud
          command: |
            echo ${GCLOUD_SERVICE_KEY} | base64 -d > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project model-159019
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Choose a tag
          command: git rev-parse --short=8 HEAD > /tmp/tag
      - run:
          name: Build base image
          command: docker build --build-arg GRAPHHOPPER_TOKEN=$GRAPHHOPPER_TOKEN --build-arg GIT_USER_ID=$GIT_USER_ID --build-arg GIT_PERSONAL_ACCESS=$GIT_PERSONAL_ACCESS . -f Dockerfile.base -t us.gcr.io/model-159019/gh:$(cat /tmp/tag)
      - run:
          name: Build server image
          command: docker build --build-arg BASE_IMAGE_TAG=$(cat /tmp/tag) . -f Dockerfile.server -t us.gcr.io/model-159019/gh:$(cat /tmp/tag)-server
      - run:
          name: Push base image
          command: gcloud docker -- push us.gcr.io/model-159019/gh:$(cat /tmp/tag)
      - run:
          name: Push server image
          command: gcloud docker -- push us.gcr.io/model-159019/gh-server:$(cat /tmp/tag)

workflows:
  version: 2
  build-and-publish:
    jobs:
      - publish-docker
