# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  publish-docker:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: &setup_gcloud
          name: Setup gcloud
          command: |
            echo ${GCLOUD_SERVICE_KEY} | base64 -d > ${HOME}/gcp-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
            gcloud --quiet config set project model-159019
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Choose a tag
          command: git rev-parse --short=8 HEAD > /tmp/tag
      - run:
          name: Build base image
          command: docker build --build-arg GRAPHHOPPER_TOKEN=$GRAPHHOPPER_TOKEN --build-arg GIT_USER_ID=$GIT_USER_ID --build-arg GIT_PERSONAL_ACCESS=$GIT_PERSONAL_ACCESS . -f Dockerfile.build -t us.gcr.io/model-159019/gh:$(cat /tmp/tag)_build
      - run:
          name: Download Mini Norcal Test Files
          command: ./setup_tests.sh
      - run:
          name: Run Tests
          command: |
            docker run -t -d --name testrunner us.gcr.io/model-159019/gh:$(cat /tmp/tag)_build /bin/bash
            docker exec -it testrunner /bin/bash -c "pwd"
            docker exec -it testrunner /bin/bash -c "mkdir -p ./web/test-data/gtfs"
            docker exec -it testrunner /bin/bash -c "ls -lar"
            docker cp test_gh_config.yaml testrunner:/graphhopper
            docker cp web/test-data/mini_nor_cal.osm.pbf testrunner:/graphhopper/web/test-data/
            for f in web/test-data/gtfs; do docker cp $f testrunner:/graphhopper/web/test-data/gtfs/; done
            docker exec -it testrunner /bin/bash -c "mvn test"
      - run:
          name: Build server image
          command: docker build --build-arg BASE_IMAGE=us.gcr.io/model-159019/gh:$(cat /tmp/tag)_build . -f Dockerfile.server -t us.gcr.io/model-159019/gh:$(cat /tmp/tag)
      - run:
          name: Push image
          command: gcloud docker -- push us.gcr.io/model-159019/gh:$(cat /tmp/tag)
workflows:
  version: 2
  build-and-publish:
    jobs:
      - publish-docker
