speed_factor:
  road_class_link: {true: 0.5, false: 1.0}
  road_class:
    motorway: 1.0
    trunk: 0.9
    primary: 0.2
    secondary: 0.2
    tertiary: 0.2
    residential: 0.2
    service: 0.2
    unclassified: 0.1
    road: 0.1
    other: 0.1
priority:
  road_class:
    primary: 0.8
    secondary: 0.8
    tertiary: 0.8
    residential: 0.7
    service: 0.9
    unclassified: 0.1
    road: 0.1
    other: 0.1
