# Configuration file for standard GraphHopper routers.
# 1 profile loaded with default speeds is defined for each vehicle type

graphhopper:
  datareader.file: {{ TEST_OSM }}
  gtfs.file: {{ TEST_GTFS }}
  gtfs.max_transfer_interpolation_walk_time_seconds: 300
  graph.location: transit_data/graphhopper
  routing.max_visited_nodes: 1500000
  graph.vehicles: car,bike,foot,truck,small_truck
  graph.encoded_values: road_class,road_class_link
  prepare.ch.threads: 16
  import.osm.ignored_highways:

  # Uncomment this if the export was done with turn-restriction-aware contraction hierarchies
  # prepare.ch.edge_based: edge_and_node
  # graph.flag_encoders: car|turn_costs=true
  # graph.bytes_for_flags: 64

  # Profiles specifying vehicle and weightings for each mode type.
  custom_model_folder: ./test-data # mvn tests run from the /web folder
  profiles:
    - name: car_default  # needed for comparison against Thurton Drive custom speeds profile
      vehicle: car
      weighting: fastest
    - name: car  # "car" profile name required for PT routing with custom access/egress mode
      vehicle: car
      weighting: custom
      custom_model_files: [local_car_custom_model.json]
    - name: car_freeway
      vehicle: car
      weighting: custom
      custom_model_files: [freeway_car_custom_model.json]
    - name: car_custom_fast_thurton_drive
      vehicle: car_custom_fast_thurton_drive
      weighting: fastest
      # sets a very high speed for Thurton Drive in Roseville (OSM way id 10485465)
      custom_speed_file: test-data/custom_speeds/custom_fast_thurton_drive_speed.csv # mvn tests run from the /web folder
    - name: car_custom_closed_baseline_road
      vehicle: car_custom_closed_baseline_road
      weighting: fastest
      # sets a zero speed for a section of Baseline Road in Roseville (OSM way id 76254223)
      custom_speed_file: test-data/custom_speeds/baseline_road_zero_speed.csv # mvn tests run from the /web folder
    - name: bike
      vehicle: bike
      weighting: fastest
    - name: foot
      vehicle: foot
      weighting: fastest
    - name: truck_default # needed for comparison against Thurton Drive custom speeds profile
      vehicle: truck
      weighting: fastest
    - name: truck_custom_fast_thurton_drive
      vehicle: truck_custom_fast_thurton_drive
      weighting: fastest
      # sets a very high speed for Thurton Drive in Roseville (OSM way id 10485465)
      custom_speed_file: test-data/custom_speeds/custom_fast_thurton_drive_speed.csv # mvn tests run from the /web folder
    - name: small_truck_default # needed for comparison against Thurton Drive custom speeds profile
      vehicle: small_truck
      weighting: fastest
    - name: small_truck_custom_fast_thurton_drive
      vehicle: small_truck_custom_fast_thurton_drive
      weighting: fastest
      # sets a very high speed for Thurton Drive in Roseville (OSM way id 10485465)
      custom_speed_file: test-data/custom_speeds/custom_fast_thurton_drive_speed.csv # mvn tests run from the /web folder

  profiles_ch:
    - profile: car_default
    - profile: car
    - profile: car_freeway
    - profile: car_custom_fast_thurton_drive
    - profile: car_custom_closed_baseline_road
    - profile: bike
    - profile: foot
    - profile: truck_default
    - profile: truck_custom_fast_thurton_drive
    - profile: small_truck_default
    - profile: small_truck_custom_fast_thurton_drive

server:
  min_threads: 4
  max_threads: 8
  application_connectors:
    - type: http
      port: 8998
      # for security reasons bind (localhost does not work with k8s svcs)
      bind_host: 0.0.0.0
      acceptor_threads: 1
      selector_threads: 2
      accept_queue_size: 8
  request_log:
    appenders: []
