name: Build GTFS Validator Image
on: [push]
jobs:
  build:
    name: Build GTFS Validator Base Image
    runs-on: macos-latest
    steps:
      - name: Login to GCP
        # Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          version: "297.0.1" # Fix https://github.com/google-github-actions/setup-gcloud/issues/128
      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-graphhopper-buildx-${{ github.sha}}
          restore-keys: |
            ${{ runner.os }}-graphhopper-buildx

      - name: Download USA OSM cutout
        run: gsutil -m -o "GSUtil:parallel_process_count=1" cp ${{ secrets.USA_OSM_PATH }} ./full_usa.osm.pbf

      - name: Build + push the GTFS validator image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.validate
          tags: "us.gcr.io/model-159019/gh:${{ github.sha }}-gtfs-validator"
          build-args: |
            BASE_IMAGE=us.gcr.io/model-159019/gh:${{ github.sha }}-server-dev
