name: Functional Test
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:
  push:

jobs:
  wtf:
    runs-on: ubuntu-latest
    name: "Show me what is going on"
    if:  github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/original-direction'
    steps:
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.ref }}
  wtf2:
    runs-on: ubuntu-latest
    name: "Job that should always run"
    steps:
      - run: echo "Nothing to see here"
